### ISSUE TITLE
有用的 CSS 片段及说明

### ISSUE THREAD

**Issue by nicejade** [nicejade/experience-precipitate#17]
## 如何用 CSS 实现毛玻璃效果

基于 `backdrop-filter` 实现，具体兼容情况，可以参见：[CSS Backdrop Filter](https://caniuse.com/#search=backdrop-filter)。

```css
.frosted-glass {
	/* Safari for macOS & iOS */
    -webkit-backdrop-filter: blur(5px); 
    /* Google Chrome */
    backdrop-filter: blur(5px); 
    /* 设置背景半透明黑色 */
    background: rgba(0, 0, 0, 0.8); 
}
```
