### ISSUE TITLE
docker-compose config # Node, Mongo, Redis, Nginx

### ISSUE THREAD

**Issue by nicejade** [nicejade/experience-precipitate#9]
```json
{
  "lerna": "3.0.3",
  "packages": [
    "client",
    "server"
  ],
  "ignoreChanges": [
    "**/__tests__/**",
    "**/*.md"
  ],
  "version": "0.0.0"
}
```

```yml
# Node, Mongo, Redis, Nginx

version: "2"
services:
  server:
    image: node:carbon
    restart: on-failure
    ports:
      - "4000:4000"
    links:
      - mongodb
      - redis
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./server:/home/node/YourProjectName/
    working_dir: /home/node/YourProjectName
    command: yarn server
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - server
    networks:
      - backend
    volumes:
      - ./server/public:/home/node/YourProjectName/public/
      - ./nginx/default.conf:/etc/nginx/conf.d/YourProjectName.conf
    ports:
      - "8888:8888"
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  mongodb:
    image: mongo:4.0.1
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db/
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  redis:
    image: redis:4.0.11
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - redis:/data/
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

networks:
  backend:

volumes:
  mongodb:
  redis:

```

**Comment by nicejade** [comment]
```yml
version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "8866:8866"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/quickqapp.conf
    links:
      - ghost
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  ghost:
    image: ghost:2.9.1
    container_name: ghost
    hostname: ghost
    volumes:
      - ./content:/var/lib/ghost/content
      - ./config.production.json:/var/lib/ghost/config.production.json:z #overwrite default settings 
    working_dir: /var/lib/ghost
    restart: always
    ports:
      - "2368:2368"
    environment:
      - NODE_ENV:production

volumes:
  ghost:
  nginx:
```

```json
# config.production.json
{
  "url": "http://localhost:2368",
  "server": {
    "host": "0.0.0.0",
    "port": 2368
  },
  "paths": {
    "contentPath": "/var/lib/ghost/content"
  },
  "database": {
    "client": "sqlite3",
    "connection": {
      "filename": "content/data/ghost.db"
    },
    "useNullAsDefault": true,
    "debug": false
  },
  "mail": {
    "transport": "SMTP",
    "options": {
      "host": "smtp_host",
      "port": 25,
      "auth": {
        "user": "your_email",
        "pass": "your_email_pass"
      }
    }
  }
}
```

详情可参见 [Migrating Ghost to Docker](https://angristan.xyz/migrating-ghost-to-docker/)。
